"use strict";
let csrf = "";
const view = document.querySelector("#view"), message = document.querySelector("#message");
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
async function api(path,data){const opts=data===undefined?{}:{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify(data)};const r=await fetch(path,opts);const x=await r.json();if(!r.ok)throw Error(x.error||"请求失败");if(x.csrf_token)csrf=x.csrf_token;return x;}
function form(title,fields,submit){const f=el("form");f.append(el("h2",title));for(const [name,label,type,value]of fields){const l=el("label",label+" ");const i=el(type==="textarea"?"textarea":"input");i.name=name;if(type!=="textarea")i.type=type||"text";if(type==="checkbox")i.checked=!!value;else if(value!==undefined)i.value=value;l.append(i);f.append(l);}f.append(el("button","保存 / 提交"));f.addEventListener("submit",async e=>{e.preventDefault();message.textContent="";try{await submit(f);message.textContent="操作成功";}catch(x){message.textContent=x.message;}});view.append(f);return f;}
function val(f,name){return f.elements.namedItem(name).value;}
function button(parent,label,run){const b=el("button",label);b.type="button";b.onclick=async()=>{try{await run();message.textContent="操作成功";}catch(e){message.textContent=e.message;}};parent.append(b);}
async function fileData(input){const f=input.files[0];if(!f)return undefined;if(f.size>1048576)throw Error("单个媒体不能超过1MiB");const b=new Uint8Array(await f.arrayBuffer());let s="";for(let i=0;i<b.length;i+=8192)s+=String.fromCharCode(...b.subarray(i,i+8192));return btoa(s);}
async function render(){
 view.replaceChildren();const page=document.body.dataset.page;
 if(page===""){const s=await api("/api/site");view.append(el("h2",s.title),el("p",s.intro),el("p",s.notice));return;}
 if(page==="login"||page==="register"){const fields=[["email","邮箱","email"],["password","密码（10–72字节）","password"]];if(page==="register")fields.push(["name","昵称","text"]);form(page==="login"?"粉丝登录":"成为粉丝",fields,async f=>{const d={Email:val(f,"email"),Password:val(f,"password")};if(page==="register")d.Name=val(f,"name");await api("/api/"+page,d);location.href="/profile";});return;}
 if(page==="profile"){const u=await api("/api/me");view.append(el("p",u.email));form("我的资料",[["name","昵称","text",u.name],["bio","简介","textarea",u.bio]],async f=>{await api("/api/me",{Name:val(f,"name"),Bio:val(f,"bio")});});return;}
 if(page==="music"){view.append(el("h2","音乐试听 · 自产测试音频"));const xs=await api("/api/tracks");if(!xs.length)view.append(el("p","暂未发布音乐"));for(const x of xs){const a=el("article");a.append(el("h3",x.title));const player=el("audio");player.controls=true;player.src=x.url;a.append(player);view.append(a);}return;}
 if(page==="albums"){view.append(el("h2","粉丝相册"));const xs=await api("/api/albums");if(!xs.length)view.append(el("p","暂未发布相册"));for(const x of xs){const a=el("article");a.append(el("h3",x.title),el("p",x.description));for(const p of x.photos){const image=el("img");image.src=p.url;image.alt=p.caption;a.append(image,el("p",p.caption));}view.append(a);}return;}
 if(page==="admin"){
 const c=await api("/api/admin/content");const users=await api("/api/admin/users");view.append(el("h2","内容管理"));
 form("首页文案",[["title","站名","text",c.title],["intro","介绍","textarea",c.intro]],async f=>{await api("/api/admin/site",{Title:val(f,"title"),Intro:val(f,"intro")});});
 form("音乐：新增或编辑（留空ID为新增）",[["id","记录ID","text"],["title","标题","text"],["audio","PCM WAV（≤1MiB）","file"],["published","发布","checkbox"]],async f=>{await api("/api/admin/tracks",{ID:val(f,"id"),Title:val(f,"title"),Audio:await fileData(f.elements.audio),Published:f.elements.published.checked});await render();});
 for(const t of c.tracks){const row=el("article",t.title+" · "+t.id+" · "+(t.published?"已发布":"草稿"));button(row,t.published?"下架":"发布",async()=>{await api("/api/admin/tracks",{ID:t.id,Title:t.title,Published:!t.published});await render();});button(row,"删除音乐",async()=>{await api("/api/admin/delete",{Kind:"track",ID:t.id});await render();});view.append(row);}
 form("相册：新增或编辑",[["id","相册ID（新增留空）","text"],["title","标题","text"],["description","说明","textarea"],["published","发布","checkbox"]],async f=>{await api("/api/admin/albums",{ID:val(f,"id"),Title:val(f,"title"),Description:val(f,"description"),Published:f.elements.published.checked});await render();});
 form("添加照片",[["album","上方列表的相册ID","text"],["caption","说明","text"],["photo","PNG或JPEG（≤1MiB）","file"]],async f=>{await api("/api/admin/photos",{Album:val(f,"album"),Caption:val(f,"caption"),Data:await fileData(f.elements.photo)});await render();});
 for(const al of c.albums){const row=el("article",al.title+" · "+al.id+" · "+(al.published?"已发布":"草稿"));button(row,al.published?"下架相册":"发布相册",async()=>{await api("/api/admin/albums",{ID:al.id,Title:al.title,Description:al.description,Published:!al.published});await render();});button(row,"删除相册",async()=>{await api("/api/admin/delete",{Kind:"album",ID:al.id});await render();});for(const p of al.photos){const sub=el("p",p.caption+" · "+p.id);button(sub,"删除照片",async()=>{await api("/api/admin/delete",{Kind:"photo",ID:p.id});await render();});row.append(sub);}view.append(row);}
 view.append(el("h2","粉丝管理"));for(const u of users){const row=el("p",u.email+" · "+u.name+" · "+(u.enabled?"已启用":"已禁用"));if(!u.admin)button(row,u.enabled?"禁用":"启用",async()=>{await api("/api/admin/user-state",{ID:u.id,Enabled:!u.enabled});await render();});view.append(row);}
 }
}
(async()=>{try{const s=await api("/api/session");const out=document.querySelector("#logout");out.hidden=!s.user;out.onclick=async()=>{try{await api("/api/logout",{});location.href="/";}catch(e){message.textContent=e.message;}};await render();}catch(e){message.textContent=e.message;}})();
