package main

import (
 "bytes"
 "encoding/binary"
 "encoding/json"
 "errors"
 "image"
 "image/color"
 "image/png"
 "net/http"
 "net/http/httptest"
 "os"
 "path/filepath"
 "strings"
 "sync"
 "testing"
 "time"
)

type client struct { t *testing.T; a *App; cookies map[string]*http.Cookie; csrf string }
func(c *client) request(verb,path string,in any,headers map[string]string)*httptest.ResponseRecorder {
 var b []byte;if in!=nil{b,_=json.Marshal(in)};r:=httptest.NewRequest(verb,"http://fans.local"+path,bytes.NewReader(b));if in!=nil{r.Header.Set("Content-Type","application/json");r.Header.Set("X-CSRF-Token",c.csrf)}
 for k,v:=range headers{r.Header.Set(k,v)};for _,v:=range c.cookies{r.AddCookie(v)};w:=httptest.NewRecorder();c.a.ServeHTTP(w,r)
 for _,v:=range w.Result().Cookies(){if v.MaxAge<0{delete(c.cookies,v.Name)}else{c.cookies[v.Name]=v}}
 var data map[string]any;if json.Unmarshal(w.Body.Bytes(),&data)==nil{if x,ok:=data["csrf_token"].(string);ok{c.csrf=x}};return w
}
func(c *client) expect(w *httptest.ResponseRecorder,code int){c.t.Helper();if w.Code!=code{c.t.Fatalf("want status %d got %d: %.250s",code,w.Code,w.Body.String())}}
func(c *client) post(path string,in any,code int)*httptest.ResponseRecorder{w:=c.request("POST",path,in,nil);c.expect(w,code);return w}
func newClient(t *testing.T,a *App)*client{c:=&client{t:t,a:a,cookies:map[string]*http.Cookie{}};c.expect(c.request("GET","/api/session",nil,nil),200);return c}
func environment(t *testing.T)(*App,*client,string){t.Helper();s,e:=OpenStore(t.TempDir());if e!=nil{t.Fatal(e)};phrase:=randomID()[:24];if e=s.Bootstrap("admin@example.invalid",phrase);e!=nil{t.Fatal(e)};a:=NewApp(s,false);c:=newClient(t,a);c.post("/api/login",map[string]any{"Email":"admin@example.invalid","Password":phrase},200);return a,c,phrase}
func object(w *httptest.ResponseRecorder)map[string]any{var x map[string]any;_ = json.Unmarshal(w.Body.Bytes(),&x);return x}
func array(w *httptest.ResponseRecorder)[]any{var x []any;_ = json.Unmarshal(w.Body.Bytes(),&x);return x}
func fan(t *testing.T,a *App)(*client,string,string){c:=newClient(t,a);phrase:=randomID()[:24];email:=randomID()[:8]+"@example.invalid";c.post("/api/register",map[string]any{"Email":email,"Password":phrase,"Name":"新粉丝"},201);return c,email,phrase}
func wave()[]byte{b:=make([]byte,44+800);copy(b,"RIFF");binary.LittleEndian.PutUint32(b[4:],uint32(len(b)-8));copy(b[8:],"WAVEfmt ");binary.LittleEndian.PutUint32(b[16:],16);binary.LittleEndian.PutUint16(b[20:],1);binary.LittleEndian.PutUint16(b[22:],1);binary.LittleEndian.PutUint32(b[24:],8000);binary.LittleEndian.PutUint32(b[28:],16000);binary.LittleEndian.PutUint16(b[32:],2);binary.LittleEndian.PutUint16(b[34:],16);copy(b[36:],"data");binary.LittleEndian.PutUint32(b[40:],800);return b}
func picture()[]byte{m:=image.NewRGBA(image.Rect(0,0,4,4));m.Set(0,0,color.RGBA{120,30,90,255});var b bytes.Buffer;_ = png.Encode(&b,m);return b.Bytes()}
func createTrack(c *client,published bool)string{return object(c.post("/api/admin/tracks",map[string]any{"Title":"自产测试试听","Published":published,"Audio":wave()},200))["id"].(string)}
func createAlbum(c *client,published bool)string{return object(c.post("/api/admin/albums",map[string]any{"Title":"测试相册","Description":"自制色块图片","Published":published},200))["id"].(string)}
func createPhoto(c *client,album string)string{return object(c.post("/api/admin/photos",map[string]any{"Album":album,"Caption":"自制测试图片","Data":picture()},200))["id"].(string)}

func TestPublicPagesAndNativeAssets(t *testing.T){a,_,_:=environment(t);c:=newClient(t,a);for _,p:=range []string{"/","/music","/albums","/login","/register"}{w:=c.request("GET",p,nil,nil);c.expect(w,200);if !strings.Contains(w.Body.String(),"非官方"){t.Fatal("missing unofficial notice")}};for _,p:=range []string{"/assets/app.js","/assets/style.css"}{c.expect(c.request("GET",p,nil,nil),200)};c.expect(c.request("GET","/missing",nil,nil),404);c.expect(c.request("GET","/admin",nil,nil),303)}
func TestRegistrationProfileLoginAndLogout(t *testing.T){a,_,_:=environment(t);c,email,phrase:=fan(t,a);before:=c.cookies["fans_session"].Value;c.post("/api/me",map[string]string{"Name":"更新昵称","Bio":"喜欢音乐"},200);c.post("/api/logout",map[string]string{},200);c.expect(c.request("GET","/api/me",nil,nil),403);c.cookies["fans_session"]=&http.Cookie{Name:"fans_session",Value:before};c.expect(c.request("GET","/api/me",nil,nil),403);c.expect(c.request("GET","/api/session",nil,nil),200);c.post("/api/login",map[string]string{"Email":email,"Password":phrase},200);if object(c.request("GET","/api/me",nil,nil))["name"]!="更新昵称"{t.Fatal("profile lost")}}
func TestPasswordIsSaltedNotPlaintext(t *testing.T){a,_,phrase:=environment(t);st:=a.store.Snapshot();for _,u:=range st.Users{if u.PasswordHash==phrase||len(u.PasswordHash)!=64||len(u.Salt)!=64{t.Fatal("invalid password representation")}};raw,e:=os.ReadFile(a.store.path);if e!=nil{t.Fatal(e)};if bytes.Contains(raw,[]byte(phrase)){t.Fatal("plaintext persisted")}}
func TestCaseInsensitiveDuplicateAndBadInputs(t *testing.T){a,_,phrase:=environment(t);c:=newClient(t,a);c.post("/api/register",map[string]string{"Email":" ADMIN@example.invalid ","Password":phrase},409);for _,in:=range []map[string]string{{"Email":"bad","Password":phrase},{"Email":"ok@example.invalid","Password":"short"},{"Email":"ok@example.invalid","Password":strings.Repeat("a",73)}}{c.post("/api/register",in,400)};if len(a.store.Snapshot().Users)!=1{t.Fatal("partial account write")}}
func TestOrdinaryFanCannotAccessAdminOrAssignRole(t *testing.T){a,_,_:=environment(t);c,_,_:=fan(t,a);c.expect(c.request("GET","/api/admin/users",nil,nil),403);c.post("/api/admin/site",map[string]string{"Title":"denied"},403);c.post("/api/me",map[string]any{"Name":"x","Admin":true},400);c.post("/api/register",map[string]any{"Email":"other@example.invalid","Password":randomID()[:24],"Admin":true},400);for _,u:=range a.store.Snapshot().Users{if u.Email!="admin@example.invalid"&&u.Admin{t.Fatal("privilege escalation")}}}
func TestProfileOnlyModifiesCurrentAccount(t *testing.T){a,admin,_:=environment(t);c,_,_:=fan(t,a);before:=object(admin.request("GET","/api/me",nil,nil));c.post("/api/me",map[string]any{"Name":"wrong","ID":before["id"]},400);c.post("/api/me",map[string]string{"Name":strings.Repeat("字",81)},400);if object(admin.request("GET","/api/me",nil,nil))["name"]!=before["name"]{t.Fatal("cross-user update")}}
func TestCSRFMethodOriginAndCookieFlags(t *testing.T){a,c,_:=environment(t);cookie:=c.cookies["fans_session"];if !cookie.HttpOnly||cookie.SameSite!=http.SameSiteStrictMode{t.Fatal("cookie flags")};c.expect(c.request("POST","/api/admin/site",map[string]string{"Title":"x"},map[string]string{"X-CSRF-Token":""}),403);c.expect(c.request("POST","/api/admin/site",map[string]string{"Title":"x"},map[string]string{"Origin":"https://evil.invalid"}),403);c.expect(c.request("GET","/api/logout",nil,nil),405);a.secure=true;g:=newClient(t,a);if !g.cookies["fans_session"].Secure{t.Fatal("secure cookie not set")}}
func TestStrictJSONAndBodyBudget(t *testing.T){_,c,_:=environment(t);c.post("/api/admin/site",map[string]any{"Title":"x","Unexpected":true},400);c.expect(c.request("POST","/api/admin/site",map[string]string{"Title":"x"},map[string]string{"Content-Type":"text/plain"}),415);c.post("/api/admin/site",map[string]string{"Title":"x","Intro":strings.Repeat("x",(2<<20)+1)},400)}
func TestDisableReenableCannotResurrectCookie(t *testing.T){a,admin,_:=environment(t);c,email,phrase:=fan(t,a);id:=object(c.request("GET","/api/me",nil,nil))["id"];old:=*c.cookies["fans_session"];admin.post("/api/admin/user-state",map[string]any{"ID":id,"Enabled":false},200);c.expect(c.request("GET","/api/me",nil,nil),403);g:=newClient(t,a);g.post("/api/login",map[string]string{"Email":email,"Password":phrase},403);admin.post("/api/admin/user-state",map[string]any{"ID":id,"Enabled":true},200);c.cookies["fans_session"]=&old;c.expect(c.request("GET","/api/me",nil,nil),403);g.post("/api/login",map[string]string{"Email":email,"Password":phrase},200)}
func TestLateSessionCreationStillBindsRevocationGeneration(t *testing.T){a,admin,_:=environment(t);c,_,_:=fan(t,a);me:=object(c.request("GET","/api/me",nil,nil));u:=a.store.Snapshot().Users[me["id"].(string)];admin.post("/api/admin/user-state",map[string]any{"ID":u.ID,"Enabled":false},200);admin.post("/api/admin/user-state",map[string]any{"ID":u.ID,"Enabled":true},200);r:=httptest.NewRequest("GET","/",nil);w:=httptest.NewRecorder();a.newSession(w,r,u.ID,u.SessionVersion);g:=newClient(t,a);g.cookies["fans_session"]=w.Result().Cookies()[0];g.expect(g.request("GET","/api/me",nil,nil),403)}
func TestAdministratorCannotDisableOwnManagementAccess(t *testing.T){_,c,_:=environment(t);id:=object(c.request("GET","/api/me",nil,nil))["id"];c.post("/api/admin/user-state",map[string]any{"ID":id,"Enabled":false},403);c.expect(c.request("GET","/api/admin/users",nil,nil),200)}
func TestExpiredAndForgedSessionDenied(t *testing.T){a,c,_:=environment(t);a.now=func()time.Time{return time.Now().Add(25*time.Hour)};c.expect(c.request("GET","/api/me",nil,nil),403);c.cookies["fans_session"]=&http.Cookie{Name:"fans_session",Value:randomID()};c.expect(c.request("GET","/api/me",nil,nil),403)}
func TestDraftTrackAndAlbumRemainPrivate(t *testing.T){a,admin,_:=environment(t);track:=createTrack(admin,false);album:=createAlbum(admin,false);photo:=createPhoto(admin,album);g:=newClient(t,a);if len(array(g.request("GET","/api/tracks",nil,nil)))!=0{t.Fatal("draft music visible")};if len(array(g.request("GET","/api/albums",nil,nil)))!=0{t.Fatal("draft album visible")};for _,p:=range []string{"/media/tracks/"+track,"/api/albums/"+album,"/media/photos/"+photo}{g.expect(g.request("GET",p,nil,nil),404)}}
func TestAudioGetHeadRangeAndInvalidRange(t *testing.T){a,admin,_:=environment(t);id:=createTrack(admin,true);g:=newClient(t,a);p:="/media/tracks/"+id;w:=g.request("GET",p,nil,nil);g.expect(w,200);if !bytes.Equal(w.Body.Bytes(),wave()){t.Fatal("audio mismatch")};w=g.request("HEAD",p,nil,nil);g.expect(w,200);if w.Body.Len()!=0{t.Fatal("HEAD contains body")};w=g.request("GET",p,nil,map[string]string{"Range":"bytes=0-15"});g.expect(w,206);if !bytes.Equal(w.Body.Bytes(),wave()[:16]){t.Fatal("range mismatch")};g.expect(g.request("GET",p,nil,map[string]string{"Range":"bytes=999999-"}),416)}
func TestPublishUnpublishEditAndDeleteMusic(t *testing.T){a,c,_:=environment(t);id:=createTrack(c,false);c.post("/api/admin/tracks",map[string]any{"ID":id,"Title":"new title","Published":true},200);g:=newClient(t,a);if len(array(g.request("GET","/api/tracks",nil,nil)))!=1{t.Fatal("missing music")};c.post("/api/admin/tracks",map[string]any{"ID":id,"Title":"new title","Published":false},200);g.expect(g.request("GET","/media/tracks/"+id,nil,nil),404);c.post("/api/admin/delete",map[string]string{"Kind":"track","ID":id},200);g.expect(g.request("GET","/media/tracks/"+id,nil,nil),404);c.post("/api/admin/delete",map[string]string{"Kind":"track","ID":id},404)}
func TestAlbumPhotoPublicationAndCascadeRemoval(t *testing.T){a,c,_:=environment(t);id:=createAlbum(c,true);ph:=createPhoto(c,id);g:=newClient(t,a);w:=g.request("GET","/media/photos/"+ph,nil,nil);g.expect(w,200);if !bytes.Equal(w.Body.Bytes(),picture()){t.Fatal("photo mismatch")};c.post("/api/admin/albums",map[string]any{"ID":id,"Title":"下架","Published":false},200);g.expect(g.request("GET","/media/photos/"+ph,nil,nil),404);c.post("/api/admin/albums",map[string]any{"ID":id,"Title":"发布","Published":true},200);c.post("/api/admin/delete",map[string]string{"Kind":"album","ID":id},200);g.expect(g.request("GET","/media/photos/"+ph,nil,nil),404);g.expect(g.request("GET","/api/albums/"+id,nil,nil),404)}
func TestDeleteSinglePhotoKeepsAlbum(t *testing.T){a,c,_:=environment(t);al:=createAlbum(c,true);ph:=createPhoto(c,al);c.post("/api/admin/delete",map[string]string{"Kind":"photo","ID":ph},200);g:=newClient(t,a);g.expect(g.request("GET","/media/photos/"+ph,nil,nil),404);g.expect(g.request("GET","/api/albums/"+al,nil,nil),200)}
func TestRejectInvalidMediaAndAbsentAssociations(t *testing.T){_,c,_:=environment(t);al:=createAlbum(c,false);for _,data:=range [][]byte{[]byte("not media"),bytes.Repeat([]byte{1},(1<<20)+1)}{c.post("/api/admin/tracks",map[string]any{"Title":"bad","Audio":data},400);c.post("/api/admin/photos",map[string]any{"Album":al,"Data":data},400)};c.post("/api/admin/photos",map[string]any{"Album":"missing","Data":picture()},404)}
func TestSiteEditingEscapesHTMLAndScriptUsesTextNodes(t *testing.T){a,c,_:=environment(t);c.post("/api/admin/site",map[string]string{"Title":"<script>alert(1)</script>","Intro":"updated"},200);g:=newClient(t,a);w:=g.request("GET","/",nil,nil);g.expect(w,200);if strings.Contains(w.Body.String(),"<script>alert(1)</script>"){t.Fatal("unescaped title")};js,_:=assets.ReadFile("web/app.js");if bytes.Contains(js,[]byte("innerHTML"))||!bytes.Contains(js,[]byte("textContent")){t.Fatal("unsafe dynamic content renderer")};if object(g.request("GET","/api/site",nil,nil))["intro"]!="updated"{t.Fatal("site edit not visible")}}
func TestRestartPersistsEntitiesButDropsSessions(t *testing.T){a,c,_:=environment(t);track:=createTrack(c,true);al:=createAlbum(c,true);ph:=createPhoto(c,al);dir:=filepath.Dir(a.store.path);s,e:=OpenStore(dir);if e!=nil{t.Fatal(e)};b:=NewApp(s,false);c.a=b;c.expect(c.request("GET","/api/me",nil,nil),403);g:=newClient(t,b);g.expect(g.request("GET","/media/tracks/"+track,nil,nil),200);g.expect(g.request("GET","/media/photos/"+ph,nil,nil),200);before:=s.Snapshot();if e=s.Bootstrap("other@example.invalid",randomID());e!=nil{t.Fatal(e)};if len(s.Snapshot().Users)!=len(before.Users){t.Fatal("bootstrap replaced user set")}}
func TestPersistenceFailureNeverPublishesPartialMutation(t *testing.T){a,_,_:=environment(t);before:=a.store.Snapshot().Title;disk,_:=os.ReadFile(a.store.path);a.store.persist=func([]byte)error{return errors.New("injected disk failure")};if e:=a.store.Update(func(s *State)error{s.Title="should not commit";return nil});e==nil{t.Fatal("missing persistence error")};if a.store.Snapshot().Title!=before{t.Fatal("memory partially committed")};after,_:=os.ReadFile(a.store.path);if !bytes.Equal(disk,after){t.Fatal("disk partially committed")}}
func TestConcurrentDuplicateRegistrationAndContentWrites(t *testing.T){a,_,_:=environment(t);phrase:=randomID();var wg sync.WaitGroup;var mu sync.Mutex;success:=0;for i:=0;i<4;i++{wg.Add(1);go func(){defer wg.Done();_,e:=a.store.Register("unique@example.invalid",phrase,"并发",false);if e==nil{mu.Lock();success++;mu.Unlock()}else if !errors.Is(e,errConflict){t.Error(e)}}()};wg.Wait();if success!=1{t.Fatalf("duplicate registrations %d",success)};for i:=0;i<12;i++{wg.Add(1);go func(){defer wg.Done();if e:=a.store.Update(func(s *State)error{id:=randomID();s.Tracks[id]=Track{ID:id,Title:"parallel",Audio:wave()};return nil});e!=nil{t.Error(e)}}()};wg.Wait();if len(a.store.Snapshot().Tracks)!=12{t.Fatal("lost update")};if _,e:=OpenStore(filepath.Dir(a.store.path));e!=nil{t.Fatal(e)}}
func TestCorruptStorageAndSymlinkFailClosed(t *testing.T){d:=t.TempDir();p:=filepath.Join(d,"state.json");if e:=os.WriteFile(p,[]byte("broken"),0600);e!=nil{t.Fatal(e)};if _,e:=OpenStore(d);e==nil{t.Fatal("corruption accepted")};os.Remove(p);if e:=os.Symlink(filepath.Join(d,"elsewhere"),p);e!=nil{t.Fatal(e)};if _,e:=OpenStore(d);e==nil{t.Fatal("symlink accepted")}}
func TestCompleteFanAndAdminJourney(t *testing.T){a,admin,_:=environment(t);c,_,_:=fan(t,a);admin.post("/api/admin/site",map[string]string{"Title":"杨千嬅粉丝站","Intro":"欢迎粉丝"},200);track:=createTrack(admin,true);al:=createAlbum(admin,true);ph:=createPhoto(admin,al);c.post("/api/me",map[string]string{"Name":"粉丝一号","Bio":"喜欢音乐"},200);for _,p:=range []string{"/music","/albums","/profile","/api/tracks","/api/albums/"+al,"/media/tracks/"+track,"/media/photos/"+ph}{c.expect(c.request("GET",p,nil,nil),200)};id:=object(c.request("GET","/api/me",nil,nil))["id"];admin.post("/api/admin/user-state",map[string]any{"ID":id,"Enabled":false},200);c.expect(c.request("GET","/api/me",nil,nil),403);c.expect(c.request("GET","/music",nil,nil),200)}
