"""From-zero fan-site scenario through formal Skills; not a Runtime fixture."""
from pathlib import Path
from datetime import datetime,timezone
import argparse,hashlib,json,os,re,shutil,subprocess,sys
from scenario_io import ScenarioIO
p=argparse.ArgumentParser()
for name in ('runtime','work','output','case-root'):p.add_argument('--'+name,required=True)
p.add_argument('--until',default='STATUS');a=p.parse_args()
WORK=Path(a.work).resolve();CASE=Path(a.case_root).resolve()
BOUNDARY='One new unofficial fan-site Go application, local single-process JSON data and disposable Sandbox delivery; no artist media, production or external writes.'
EXECUTOR='web-realflow-fansite-executor'
if not WORK.exists():
 WORK.mkdir(parents=True);shutil.copytree(CASE/'baseline',WORK/'source')
 shutil.copytree(CASE/'candidate/vendor',WORK/'source/vendor')
 subprocess.run(['git','init','-q'],cwd=WORK,check=True);subprocess.run(['git','add','source'],cwd=WORK,check=True)
 subprocess.run(['git','-c','user.name=SDLC regression','-c','user.email=regression@example.invalid','commit','-qm','baseline: empty Go application and licensed offline dependency'],cwd=WORK,check=True)
 d=WORK/'.sdlc/authority';d.mkdir(parents=True)
 (d/'work-authorization.md').write_text('User authorized three real-flow scenarios including this from-zero fan site; after Admin and SpringGear qualification continue from their frozen baseline. User explicitly approved existing Go/tools, native JavaScript instead of jQuery, bounded application design changes, isolated implementation/testing, local Sandbox effects and delegated objective artifact review. No risk waiver, production deployment, future PASS, independent AI claim or upstream write is authorized.\n')
io=ScenarioIO(a.runtime,WORK,a.output,EXECUTOR,BOUNDARY)
from packages.sdlc_runtime import parse_canonical_artifact,parse_markdown_tables
baseline=subprocess.check_output(['git','rev-parse','HEAD'],cwd=WORK,text=True).strip()
F=lambda x:{'value':x,'basis':'observed','basis_references':['EVD-001']}
N={'none':{'basis':'confirmed','basis_references':['EVD-001']}}
prov=(WORK/'source/SOURCE.md').read_text()
ctx={'context':{'summary':'New application scaffold, Go1.23 language floor, licensed vendored PBKDF2 and no existing business implementation.',
 'project_identity':{'project_name':F('Miriam Yeung unofficial fan site'),'purpose':F('New local showcase and fan-account application for real SDLC verification'),'boundary':{**F(BOUNDARY),'basis':'confirmed'},'primary_resource_reference':F('RSC-001'),'authoritative_references':F('User-approved new-project scope; exact local versioned scaffold and vendored upstream provenance.')},
 'resources':[{'id':'RSC-001','type':'application','name':'Fan-site application','role':'primary','locator':'source','baseline_reference':baseline,'basis':'observed','basis_references':['EVD-001']}],
 'technologies':[{'id':'TEC-001','category':'runtime','name':'Go + HTML + native JavaScript','version_or_constraint':'Go language >=1.23; use existing toolchain; no npm or remote frontend dependency','purpose':'Single executable HTTP application with embedded assets','basis':'referenced','basis_references':['EVD-001']}],
 'engineering_entries':[{'id':'ENG-001','purpose':'test','command_or_entry_point':'go test -count=1 -v ./...','working_scope':'source','preconditions':'Existing Go and complete vendor files; no dependency installation during execution','basis':'confirmed','basis_references':['EVD-001']}],
 'components':[{'id':'CMP-001','name':'New single-process application','type':'application','resource_reference':'RSC-001','responsibility':'To implement public content, accounts, media and management over local state','entry_point':'source','depends_on':'None','authority_reference':'EVD-001','basis':'confirmed','basis_references':['EVD-001']}],
 'rules':N,'environments':[{'id':'ENV-001','environment':'test','purpose':'In-process HTTP tests and disposable local Sandbox','accessibility':'available','data_and_network_boundary':'Synthetic accounts and self-generated media; no network during formal tests','basis':'confirmed','basis_references':['EVD-001']}],'constraints':N,'exceptions':[]},
 'evidence':[{'id':'EVD-001','type':'source-inspection','supports_references':['RSC-001'],'source_or_producer':EXECUTOR,'reference':'SUP-001','integrity_or_digest':'sha256:'+hashlib.sha256(prov.encode()).hexdigest(),'produced_at':datetime.now(timezone.utc).isoformat(timespec='seconds'),'sensitivity_or_access':'Public scaffold and authorized synthetic data only'}],
 'supporting_members':[{'member_id':'SUP-001','canonical_name':'source-provenance.md','media_type':'text/markdown','purpose':'New-project scope, existing tools and upstream dependency source','content':prov}]}
ctxref=io.complete('000-ctx',ctx)
if a.until=='CTX':raise SystemExit(0)
requirements=[
 ('behavior','Display an unofficial Miriam Yeung themed home, music, album and account pages using Go, HTML and native JavaScript without remote page dependencies.'),
 ('behavior','Fans can register, log in, view/edit only their own profile and log out; email is normalized and unique, input limits apply.'),
 ('rule','Use explicit one-time administrator initialization; ordinary registration cannot grant roles. Only enabled admins manage users, homepage, tracks, albums and photos.'),
 ('rule','Use salted slow password derivation, random expiring opaque sessions, protected cookies, CSRF and same-origin checks. Disable revokes current and stale-generation sessions; re-enable needs a new login.'),
 ('behavior','Published WAV previews support real GET/HEAD/Range; drafts, removed and unpublished media remain inaccessible by direct URL.'),
 ('behavior','Administrators create/edit/publish/unpublish/delete albums, upload bounded PNG/JPEG photos and delete photos. Associations persist and removed albums expose no orphan images.'),
 ('behavior','Administrators can edit public site text and create/edit/publish/unpublish/delete music, and list/enable/disable fans without disabling the last management account.'),
 ('quality','Persist users, site, albums and music in a single-process local JSON store across restart. Concurrent updates preserve uniqueness and no lost writes; persistence failure does not publish partial in-memory state.'),
 ('quality','Reject unauthorized, unknown-field, oversized or malformed writes. Escape user content, bound media types and sizes, and do not expose credential material.'),
 ('constraint','Use no artist recordings/photos or real customer data; provide generated test-media tooling, complete source/license and run instructions. RLS is local Sandbox only, not application deployment.')]
acs=[
 ('Read all public pages and native assets','Pages/assets load, unofficial notice present; unauthenticated profile/admin denied.'),
 ('Register, edit profile, logout, replay cookie and login again','Own profile persists; old cookie rejected; duplicate normalized email, invalid email/password and oversized fields rejected.'),
 ('Bootstrap, normal register and try administrative routes/role injection','Only the explicitly bootstrapped administrator manages content/users; fan or forged role input does not escalate.'),
 ('Disable/re-enable, expire/replay sessions, tamper CSRF and Origin','Current and stale login generations remain revoked, invalid writes denied, required cookie flags set and no plaintext stored.'),
 ('Create a draft track, publish and retrieve full/ranged audio, then unpublish/delete','Actual bytes match; HEAD empty, valid Range206/invalid Range416; unpublished/deleted URLs404.'),
 ('Create/edit album, upload valid/invalid photo, publish/unpublish and delete','Valid photo round-trips; bad type/size/missing association rejected; no direct draft or orphan media access.'),
 ('Admin edits homepage and manages listings and fan state','Current public text reflects edits, lists show actual records, administrator disable rejected and fan disable enforced.'),
 ('Restart, race duplicate registration and content writes, inject storage failure','Entities and references survive; sessions restart invalid; exactly one duplicate account, no lost updates, rejected write preserves memory/disk.'),
 ('Send bad content types/unknown JSON fields/oversized bodies and display markup text','Requests rejected without unauthorized state changes; template and JS text nodes escape untrusted content.'),
 ('Inspect run instructions, licensing, sample generator and full combined user journey','No unlicensed media or actual secrets; source builds offline, generated media plays, whole fan/admin journey succeeds.')]
req={'context_reference':ctxref,'requirement':{'title':'从零构建杨千嬅主题非官方粉丝网站','summary':'Go/HTML/native JavaScript site: fans, music previews, albums and minimal administrator management, with real local functional tests.',
 'sources':[{'type':'conversation','content':'用户原需求：做一个杨千嬅主题个人粉丝网站，Go+jQuery+HTML，基本展示、用户（粉丝）体系、音乐试听、相册、简单后台。后续明确批准既有Go版本，必要时原生JavaScript代替jQuery，合理精简环境；目标是通用SDLC验证，不是生产上线。本次保留全部模块，限定WAV试听与PNG/JPEG相片、单进程本地JSON，三工作项衔接验证。','evidence_reference':ctxref+'/SUP-001'}],
 'goals':[{'problem':'No usable application exists in the new versioned scaffold.','outcome':'A complete local fan site with connected public/account/media/admin functions and traceable lifecycle.','success_condition':'All stated acceptance conditions pass on the current final implementation; formal VFY, local Sandbox RLS and Status agree.'}],
 'in_scope':['Public site and native frontend assets','Fans and protected administrator accounts','Bounded WAV previews and image albums','Local transactional persistence, offline tests and Sandbox lifecycle'],
 'out_of_scope':['Production hosting or payment','Artist recordings or photos','Subjective UI/UX approval','Distributed persistence, translation, SEO or feature expansion'],'affected_parties':[],
 'requirements':[{'type':t,'source_references':['SRC-001','GOAL-001'],'statement':s} for t,s in requirements],
 'acceptance_criteria':[{'requirement_references':[f'R-{n:03d}'],'condition':c,'expected_result':e} for n,(c,e) in enumerate(acs,1)],
 'dependencies':[],'profile':'full','lifecycle_applicability':[{'phase':x,'disposition':'required','host':'N/A','basis':'Multi-module design, dependency-ordered implementation, current-result verification and local Sandbox delivery.'} for x in ('DSN','PLN','IMP','VFY','RLS')],
 'open_items':[],'evidence':[],'supporting_members':[],'exceptions':[]}}
reqref=io.complete('100-req',req)
if a.until=='REQ':raise SystemExit(0)
rs=[f'{reqref}#R-{n:03d}' for n in range(1,11)];ac=[f'{reqref}#AC-{n:03d}' for n in range(1,11)]
def table(headers,rows):
 cell=lambda v:str(v).replace('\\','\\\\').replace('|','\\|').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(headers)+' |','|'+'|'.join('---' for _ in headers)+'|']+['| '+' | '.join(cell(x) for x in row)+' |' for row in rows])
points={
 '110':('Fan and administration business rules','Public users see only published media. Normal registration is always a fan; one-time private bootstrap is the only administrator entry. Login, own-profile editing, logout, management and revocation form one connected journey.','Full fan/admin journey succeeds and cross-role actions are denied.',[1,2,3,4,7]),
 '120':('Functional page journey','Routes /, /music, /albums, /login, /register, /profile and /admin are served by one escaped template. Existing native JavaScript calls same-origin JSON endpoints. User feedback shows actual server errors; no subjective design rating.','All required routes and forms map to real backend features.',[1,2,6,7]),
 '130':('View and controller wiring','Native DOM uses textContent, audio controls and image nodes. Administration exposes create/edit/publish/delete controls and file upload as bounded base64 JSON. No external scripts/CDN are required.','Public assets are local and admin operations reflect current backend state.',[1,5,6,7,9]),
 '210':('Small monolith with owned state','Use net/http, embedded HTML/JS/CSS, one Store and in-memory opaque sessions. No external service, plugin, ORM or database server. Source stages are storage/account, HTTP/media/views, then combined verification.','A single offline-built executable covers all required modules.',[1,3,8,10]),
 '220':('Implementation and dependency choices','Use Go language1.23 and vendored unchanged golang.org/x/crypto v0.31.0 PBKDF2. Random per-account salt, HMAC-SHA256600000 iterations and constant-time comparison; no new crypto algorithm. HTTP routes retain one public/admin boundary.','Password representation and concrete handlers implement the specified rules.',[2,3,4,9]),
 '230':('HTTP and media contracts','Public GET endpoints expose only projections without hashes/media bytes except dedicated media routes. Writes are POST application/json with exact field sets, 2MiB body cap and CSRF. Audio URLs support GET/HEAD/Range; photo URLs recheck published parent.','Statuses, projection fields, protected writes and stream bytes match API contracts.',[4,5,6,9]),
 '240':('Entities and persistence shape','Version1 JSON state has users, tracks, albums with inline photos and site text. Media capped1MiB and image dimension validation. Store mutation clones under a mutex, validates, writes same-dir temporary file/sync/rename, then swaps memory. Sessions remain outside persisted data.','Entity relations persist, duplicate emails and lost concurrent writes are prevented.',[2,5,6,8]),
 '310':('Account security and data minimization','Session cookies are HttpOnly/SameSiteStrict with Secure when TLS configured; raw tokens are not persisted. Server-issued independent CSRF values and Origin checks protect writes; session version increments on disable, so stale in-flight authentication cannot restore revoked sessions. Private credentials never appear in response projections. Test identities/media are synthetic.','Security/privacy negative tests reject role injection, CSRF, forged/expired/revoked sessions and unauthorized edits.',[2,3,4,9,10]),
 '330':('Failure consistency','A failed persistence step leaves both committed memory and existing file unchanged. Corrupt or linked state files fail startup; no silent reset. Restart intentionally drops all sessions while preserving content. No distributed availability claim.','Failure injection, corruption and restart tests retain the required state semantics.',[8,9]),
 '350':('Executable functional validation','24 named Go tests use real App.ServeHTTP via httptest request/response and real temporary persistence. Test fixtures are generated runtime values; do not open a socket or use remote services. Include a combined fan/admin journey plus independent negative cases.','All24 test identities pass with zero skips on the current terminal source.',list(range(1,11))),
 '410':('Local executable and Sandbox-only qualification','go build produces one executable, vendor makes execution offline. Bootstrap credentials come only from environment; default bind127.0.0.1. User can upload generated sample media using the supplied script. RLS is existing disposable local version-state target, not application installation/production deployment.','Run instructions, offline build and bounded lifecycle target are truthful.',[1,3,8,10])}
na={'140':'Chinese-only test site; no multilingual requirement or formal accessibility certification. Basic labels/HTML structure remain implemented in DOM130.','320':'No throughput/latency/capacity SLA; input size and bounded hashing concurrency are covered by DOM230/310.','340':'This is a new empty project, no existing production data or backward schema migration is requested.','420':'No production observability requirement; minimal non-sensitive start/error logs suffice.'}
domains={}
for code in ('110','120','130','140','210','220','230','240','310','320','330','340','350','410','420'):
 if code in na:domains['DOM-'+code]={'disposition':'n/a','reason':na[code],'basis_references':[reqref]};continue
 title,design,observable,indices=points[code]
 domains['DOM-'+code]={'disposition':'required','completion':'complete','responsible_role':'Application maintainer','basis_references':[rs[n-1] for n in indices],
  'design_result_markdown':'## 设计结果 Design Result\n\n### '+title+'\n\n'+design,
  'constraints_impacts':[{'type':'constraint','content':'Retain all requested modules, bounded local scope and the selected trust/consistency rules.','affected_phase':'IMP, VFY, RLS','reference':reqref}],
  'vfy_points':[{'id':'VFP-'+code+'-001','references':[ac[n-1] for n in indices],'verification_object':title,'observable_result':observable,'expected_evidence':'Named current-source tests, actual logs, immutable result and matching source/permission boundaries.'}],
  'evidence_references':[{'reference':ctxref+'/SUP-001','supports':['CHG-001','CHG-002','CHG-003'],'purpose':'Authorized new-project scope and dependency provenance'}]}
vfps=['VFP-'+c+'-001' for c in points]
objectives=[
 ('VFO-001','Accounts, authorization, session lifecycle and private profile are correct.',[2,3,4,9],['VFP-110-001','VFP-220-001','VFP-310-001']),
 ('VFO-002','Public pages, manager operations, streaming and album associations remain connected.',[1,5,6,7,10],['VFP-120-001','VFP-130-001','VFP-210-001','VFP-230-001','VFP-410-001']),
 ('VFO-003','Persistent state is restart-safe and no concurrent or failed mutation publishes invalid data.',[2,8,9],['VFP-240-001','VFP-330-001','VFP-350-001'])]
strategy='## 设计结果 Design Result\n\n### VFY 目标 VFY Objectives\n\n'+table(['ID','Kind','Requirement, AC, Goal or Intended-use References','Design or Decision References','Domain VFY Point References','可观察结果 Observable Result','风险或重要性 Risk or Importance','Method References','Pass Criteria References','Evidence Contract References'],[[i,'both',', '.join([*(ac[n-1] for n in inds),reqref+'#GOAL-001']),'CHG-001, CHG-002, CHG-003, DEC-001',', '.join(v),text,'Prevent omission or false independence between modules.','VFM-001','VPC-001','VEC-001'] for i,text,inds,v in objectives])
strategy+='\n\n### 方法选择 VFY Methods\n\n'+table(['ID','类型 Type','Disposition','方法明细 Method Detail','适用范围 Scope','方法 Method','选择依据 Selection Basis','承载位置 Host','Exception Reference'],[['VFM-001','test','required','level=integration, mode=automated','VFO-001, VFO-002, VFO-003','Run all24 actual named Go tests on the current terminal result.','One test execution exercises real HTTP handlers and storage across all modules without network.','VFY','N/A']])
strategy+='\n\n### 可验证性设计 Verifiability Design\n\nTest App.ServeHTTP, temporary real JSON persistence and independently generated WAV/PNG bytes. Source files and selectors are checked, without claiming a browser UX review.\n\n### 环境与数据 Environment and Data\n\nExisting Go, full vendor directory, OS sandbox, no network and no external database. Passwords and accounts generated per test; no real data.\n\n### 覆盖策略 Coverage Strategy\n\nCASE-TRACEABILITY maps each AC to exact Test names. Include negative auth/CSRF/role paths, draft URL denial, byte streaming, mutation failure, revocation generation, restart and concurrency. Do not infer coverage from compilation alone.\n\n### 通过条件 Pass Criteria\n\n'+table(['ID','VFY Objective','输入或条件 Input or Condition','预期结果 Expected Result','容差 Tolerance','失败条件 Failure Condition'],[['VPC-001','VFO-001, VFO-002, VFO-003','Current terminal source in isolated workspace','All24 uniquely named tests execute and pass without skip; raw evidence and source hashes are retained.','None','Failure, missing test identity, skip, stale source or unsupported containment.']])
strategy+='\n\n### Evidence Contract\n\n'+table(['ID','VFY Objective','Evidence Type','生成方或来源 Producer or Source','必要内容 Required Content','敏感性与处理 Sensitivity and Handling','保留要求 Retention Requirement','保存或引用位置 Storage or Reference'],[['VEC-001','VFO-001, VFO-002, VFO-003','Execution and immutable result','Actual Go test process','All test names/results, stdout/stderr, exit code, source hashes and OS containment','Synthetic values only; never credential/session dumps','Preserve originals plus online readable projection','VFY supporting evidence and experiment repository']])
domains['DOM-510']={'disposition':'required','completion':'complete','responsible_role':'Verification designer','basis_references':[reqref],'design_result_markdown':strategy,'constraints_impacts':[],'vfy_points':[],'evidence_references':[]}
composite=[{'domain_code':code,'subdomain':name,'disposition':dis,'basis_references':[reqref],'reason':reason,'exception_references':[]} for code,name,dis,reason in [('DOM-140','可访问性 Accessibility','n/a',na['140']),('DOM-140','国际化 Internationalization','n/a','Chinese-only scope; no translation or language switch requested.'),('DOM-310','安全 Security','required',points['310'][1]),('DOM-310','隐私 Privacy','required','Email and profile data require private access; no credentials in public output; synthetic qualification data only.'),('DOM-310','合规 Compliance','n/a','No regulated production processing; no licensing/legal certification. Preserve third-party code license and use self-generated media.')]]
design={'title':'粉丝站完整最小单体设计','summary':'Complete local public/fan/media/admin application; dependency-ordered work with exact multi-objective verification.',
 'boundary':BOUNDARY,'change_type':'new','baseline_references':[ctxref],'target_state_summary':'A runnable local Go fan site whose modules and privacy/state boundaries work together.','impact_summary':'Create only declared new application source, embedded frontend, tests and local instructions.',
 'changes':[{'id':f'CHG-{n:03d}','object_or_boundary':'resource:RSC-001','change':'add','baseline_references':[ctxref],'baseline_state':'Empty application scaffold with no business implementation.','target_state':text,'affected_domains':ds} for n,text,ds in [(1,'Transactional state, password verification, administrator bootstrap and session structures.',['DOM-210','DOM-220','DOM-240','DOM-310','DOM-330']),(2,'Functional public/account/admin HTTP endpoints, embedded pages and bounded streaming/album features.',['DOM-110','DOM-120','DOM-130','DOM-230','DOM-310','DOM-410']),(3,'Named combined and negative tests, sample-media generator and accurate operating instructions.',['DOM-350','DOM-510','DOM-410'])]],
 'decisions':[{'id':'DEC-001','requirement_references':rs,'question':'How to preserve all modules without an unavailable database, frontend build chain or invented cryptography?','options':['External database, SPA and remote assets','Go monolith with native DOM, atomic local JSON and licensed vendored PBKDF2'],'decision':'Go>=1.23, single-process local JSON transactions, ephemeral hashed-key sessions with persisted generation, native HTML/JS, and unchanged x/crypto PBKDF2; bounded WAV/PNG/JPEG.','rationale':'Fits authorized existing environment while keeping accounts, media, management and consistency truly functional.','affected_domains':['DOM-210','DOM-220','DOM-240','DOM-310','DOM-410']}],
 'traceability':[{'source_references':[r,x],'design_references':[f'CHG-{n:03d}' for n in ((1,3) if i in (2,4,8) else (2,3))]+['DOM-510'],'decision_references':['DEC-001'],'vfy_references':[v[0] for v in objectives if i in v[2]]} for i,(r,x) in enumerate(zip(rs,ac),1)],
 'domains':domains,'composite_subdomains':composite,'cross_domain_conflicts':[],'scope_expansion':False,'simplicity_rationale':'One application and local state only; no external provider, public installation or new framework.',
 'lifecycle_applicability':[{'phase':ph,'disposition':'required','host':'N/A','basis':'Three dependency-ordered implementation work items, complete current-result verification and local Sandbox.'} for ph in ('PLN','IMP','VFY','RLS')], 'evidence':[],'supporting_members':[],'open_items':[],'exceptions':[]}
dsref=io.complete('200-dsn',{'design':design},[reqref])
if a.until=='DSN':raise SystemExit(0)
s=io.read(dsref);tables=list(parse_canonical_artifact(s.payload.primary_blob).tables)
for m in s.payload.members:
 if m.media_type=='text/markdown':tables.extend(parse_markdown_tables(m.raw_bytes.decode()))
obligations=[]
for t in tables:
 for row in t.rows:
  item=row.get('ID') or row.get('Change ID')
  if isinstance(item,str) and re.fullmatch(r'(?:CHG|VFP|OBJ|OBL|EX|R|AC)-[A-Za-z0-9._-]+',item):
   ref=f'{dsref}#{item}'
   if ref not in obligations:obligations.append(ref)
work=[]
for n,phase,outcome,ids,deps,done,evidence in [
 (1,'IMP','Implement local transactional state and account core.',['CHG-001','VFP-220-001','VFP-240-001','VFP-330-001'],[],'Source compiles with licensed offline dependencies and implements the specified account/store rules.','Exact authored source and actual isolated compilation evidence.'),
 (2,'IMP','Connect pages, accounts, administrative controls and media endpoints.',['CHG-002','VFP-110-001','VFP-120-001','VFP-130-001','VFP-210-001','VFP-230-001','VFP-310-001'],['WI-001'],'Complete frontend and backend build without remote dependencies; all declared modules have handlers and pages.','Exact HTTP/asset source and actual isolated build output.'),
 (3,'IMP','Implement and execute all functional regression and operating instructions.',['CHG-003','VFP-350-001','VFP-410-001'],['WI-002'],'All24 named tests pass with zero skipped or failed tests on the complete candidate.','Actual named test output, traceability, sample generator and final immutable result.'),
 (4,'VFY','Independently verify the entire current account/media/storage scope.',vfps,['WI-003'],'All authoritative objectives and current source pass the real test method.','Fresh OS-contained full Go test execution and exact source bindings.'),
 (5,'RLS','Qualify the exact current result in the local Sandbox target.',vfps,['WI-004'],'Local target version and confirmation match the verified current result.','Actual target-side Sandbox evidence and final Status with zero blockers.')]:
 work.append({'id':f'WI-{n:03d}','target_phase':phase,'outcome':outcome,'execution_scope':['resource:RSC-001']+(['environment:local-validation'] if phase=='RLS' else []),'source_references':[dsref+'#'+x for x in ids],'constraint_references':[],'depends_on':deps,'completion_criteria':done,'expected_evidence':evidence,'responsible_role':'Application executor' if phase=='IMP' else 'Verifier' if phase=='VFY' else 'Sandbox host'})
plan={'title':'粉丝站三个工作项与完整交付计划','summary':'Core state → functional web modules → combined tests → current-result VFY → local Sandbox.',
 'profile':'full','pln_disposition':'required','delivery_scope':[{'source_artifact_reference':dsref,'inclusion_basis':'All modules and obligations of the complete selected fan-site design.'}], 'obligations':obligations,'work_items':work,'aggregated_applicability':[],
 'lifecycle_applicability':[{'phase':ph,'disposition':'required','host':'N/A','basis':'Entire scope with dependency-ordered implementation and one terminal source.'} for ph in ('IMP','VFY','RLS')],'open_items':[],'exceptions':[],'evidence':[],'supporting_members':[]}
plnref=io.complete('300-pln',{'plan':plan},[dsref])
if a.until=='PLN':raise SystemExit(0)
considerations=('Calculation Rules','Decision Rules','State Transitions','Algorithm & Invariants','Data Contract & Transformation','Boundary & Failure Handling','Effects & Consistency')
filesets=[['store.go'],['server.go','main.go','web/index.html','web/app.js','web/style.css'],['site_test.go','README.md','CASE-TRACEABILITY.md','sample_media.py']]
for n,files in enumerate(filesets,1):
 label=f'IMP-{n}'
 if label in io.state['stages']:continue
 methodpath=io.out/f'implementation-{n}.json'
 if methodpath.exists():method=json.loads(methodpath.read_text())
 else:
  ops=[]
  for name in files:
   old=WORK/'source'/name;ops.append({'resource':'RSC-001','path':name,'step':'STEP-001','op':'write_text','expected_sha256':'sha256:'+hashlib.sha256(old.read_bytes()).hexdigest() if old.exists() else 'absent','content':(CASE/'candidate'/name).read_text()})
  blocks=[{'consideration':'Boundary & Failure Handling','id':'ERR-001','trigger':'Invalid input, unauthorized operation, stale source, failed storage, compilation or test.','classification':'Visible bounded failure, never silently completed work.','handling':'Reject before invalid mutation; preserve successful committed state and exact failure evidence.','observable_result':'Denied HTTP or nonpassing runtime check; no fabricated authority.','recovery':'Correct bounded source or execution environment, then retry under the same valid scope or formal rework.'},
   {'consideration':'Effects & Consistency','id':'EFF-001','resource_or_effect':'Current source snapshot and in-application local state effects only.','order_and_condition':'Core source first, dependent web handlers next, then actual tests; writes bind exact existing content.','consistency_or_atomicity':'Store clone/validate/persist/rename precedes memory publication; runtime checkpoints each declared source effect.','idempotency':'Confirmation and retry never replay completed source operations.','failure_handling':'Keep failure evidence; no remote service, production write or history replacement.'}]
  if n<3:blocks=[{'consideration':'Decision Rules','id':'DEC-001','rules':[{'id':'DR-001','priority':'1','conditions':'missing authority, disabled/stale session, malformed input or mismatched state','outcome':'Reject without publishing changes'},{'id':'DR-002','priority':'2','conditions':'DEFAULT','outcome':'Perform the exact allowed account or content operation after validation'}]},
   {'consideration':'State Transitions','id':'STA-001','transitions':[{'id':'TR-001','current':'enabled account / published content','event':'authorized disable or unpublish/delete','next':'disabled account / hidden or removed content','effect':'Increment revocation generation or remove public visibility together with committed state','illegal_handling':'Reject unauthorized or missing entity without partial state'},{'id':'TR-002','current':'disabled account','event':'administrator re-enables','next':'enabled account with prior generation retained','effect':'Require a fresh login; old sessions stay rejected','illegal_handling':'Never restore previous authentication authority'}]},
   {'consideration':'Algorithm & Invariants','id':'ALG-001','inputs':'Validated account/content input and exact current stored state.','outputs':'Committed state or explicit rejection, with no secret material in public output.','invariants':'Unique normalized email, current session generation, published-parent media and no partial disk/memory mutation.','scale_or_limits':'Single process, bounded bodies/media, bounded concurrent derivations; no production scale claim.','pseudocode':'Load authoritative state; validate roles and inputs; clone under mutex; apply bounded mutation; persist complete bytes; publish memory only on success.'},
   {'consideration':'Data Contract & Transformation','id':'MAP-001','mappings':[{'source':'Submitted account credentials and profile','target':'Normalized private account record','transformation':'Validate email/password limits, salt and derive with vendored PBKDF2; expose only public projection','validation':'Unique email, declared lengths, protected role assignment','null_or_default':'New account enabled as fan unless explicit empty-store bootstrap'},{'source':'Submitted media and published-parent state','target':'Bounded track/album/photo records and controlled bytes','transformation':'Validate MIME/size/dimensions, persist complete association and recheck publication on reads','validation':'Reject missing parent, bad content and unauthorized changes','null_or_default':'New content draft unless explicitly published'}]},*blocks]
  names=[c for c in considerations if any(b['consideration']==c for b in blocks)]
  method={'considerations':[{'name':c,'disposition':'required' if c in names else 'n/a','basis':'Account/content rules and transactional state require the declared reasoning.' if c in names else 'Use existing vetted derivation library, no new product formula; verification work introduces no new business rule.','steps':['STEP-001'] if c in names else [],'exception':'N/A'} for c in considerations],
   'steps':[{'id':'STEP-001','order':1,'purpose':work[n-1]['outcome'],'target':['resource:RSC-001'],'basis_references':[plnref+f'#WI-{n:03d}',dsref+f'#CHG-{n:03d}'],'considerations':names,'logic':['Read current exact upstream design and resource baseline.','Implement only this dependency-ordered bounded application increment.','Run declared isolated checks and preserve complete current result and evidence.'],'expected_result':work[n-1]['completion_criteria'],'transaction_boundary':'One versioned application increment; runtime request transactions follow the approved local Store design.','failure_boundary':'Any stale source, missing authority, invalid mutation, compile failure or failed check blocks completion.','blocks':blocks}],
   'resources':[{'id':'RSC-001','root':'source'}],'operations':ops,'checks':[{'id':'CHK-001','name':'Actual offline package compilation' if n<3 else 'Complete current-source functional tests','resource':'RSC-001','kind':'project_command','cwd':'.','command':['go','test','./...'],'timeout_seconds':180}],
   'design_decision_references':[dsref+'#DEC-001'],'exceptions':[],'open_items':[]}
  methodpath.write_text(json.dumps(method,ensure_ascii=False,indent=2)+'\n')
 io.complete('400-imp',{'inputs':{'implementation':method}},[plnref]+([io.state['stages'][f'IMP-{n-1}']] if n>1 else []),label=label,binding=plnref+f'#WI-{n:03d}')
if a.until=='IMP':raise SystemExit(0)
terminal=io.state['stages']['IMP-3']+'/RESULT-RES-001'
vfy={'targets':[{'reference':dsref+'#'+i,'purpose':'both','summary':text,'source_kind':'vfo','obligation_references':[dsref+'#'+x for x in v]} for i,text,inds,v in objectives],
 'methods':[{'id':'VFM-001','title':'Current-source complete fan/admin/media/store integration','purpose':'both','target_references':[dsref+'#'+v[0] for v in objectives],'subject_references':[terminal],
 'obligation_references':sorted([dsref+'#'+x for x in [*vfps,'VFM-001','VPC-001','VEC-001']]+[plnref+f'#WI-{n:03d}' for n in (1,2,3,4)]),
 'method_type':'test','disposition':'required','execution_mode':'automated','executor_identity':EXECUTOR,'environment':{'project_root':'.','data_contract':'Vendored offline dependencies, synthetic accounts/WAV/PNG and real temporary local persistence; OS isolation, no network.'},
 'procedure':{'kind':'command','argv':['go','test','-count=1','-v','./...'],'policy':'deterministic-test-v1','workspace':'isolated-copy','network':'disabled','cwd':'source','timeout_seconds':180,'max_output_bytes':1048576},
 'pass_criteria':'All24 named tests execute on this current terminal source with zero failure, error or skip, and all three authoritative objectives pass.','evidence_requirement':'Actual named Go output and exit code, OS containment, source hashes and complete test evidence; preparation logs do not substitute.'}]}
io.verify_and_close(plnref,terminal,vfy,reqref)
